apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: guestbook-ui-http-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`guestbook.sid.k8s.test`)
      services:
        - name: guestbook-ui
          port: 80
