apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
destination:
  namespace: argocd
  server: https://kubernetes.default.svc
project: default
source:
  directory:
    jsonnet: {}
    recurse: true
  path: namespaces/argocd
  repoURL: https://github.com/jonnyhoeven/argocd.git
syncPolicy:
  manual:
    allowEmpty: true
    prune: false
    selfHeal: true
