apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
destination:
  namespace: cloudnative-pg
  server: https://kubernetes.default.svc
project: default
source:
  directory:
    jsonnet: {}
    recurse: true
  path: namespaces/cloudnative-pg
  repoURL: https://github.com/jonnyhoeven/argocd.git
syncPolicy:
  automated:
    prune: true
    selfHeal: true