apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-http-ingress
spec:
  rules:
    - host: "argo.k8s.test"
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443